### PR TITLE
Support dir-name for scala testSets

### PR DESCRIPTION
**Pull request by huggsboson**

### CODE REVIEW

**Comment by huggsboson** [comment]
@tkrullmann do I need to sign a CLA or anything?

**Comment by tkrullmann** [comment]
Thanks for the contribution!
I think there should be some check if the scala plugin is active (similar to what is done for Groovy and Kotlin), otherwise the `sourceSets.scala` expression will fail.

**Comment by huggsboson** [comment]
Good catch.   Patch set updated.  

I've obviously not been running the tests.  I'll figure out how to get those working.

**Comment by huggsboson** [comment]
I ran the tests.  I confirmed with the current PR that they run cleanly.

I also confirmed that they fail if:
1. I remove the apply plugin in the scala test.
2. I remove the scala plugin check from the main file (the MissingPropertyException you expected).

**Pull request merged**
